name: Build and Deploy Production

on:
  workflow_call:
    inputs:
      update-script:
        required: true
        type: string
      docker-database-build-arg:
        required: false
        default: false
        type: boolean

env:
  DOCKER_IMAGE_NAME: gcr.io/${{ secrets.GCE_PROJECT }}/${{ github.event.repository.name }}
  GCE_INSTANCE: prod-pd-library-services
  GCE_INSTANCE_ZONE: europe-west3-c

jobs:
  setup-build-publish-deploy:
    name: Build Production Job
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Get version from tag name'
        id: get_version
        run: |
          version=${GITHUB_REF/refs\/tags\//}
          echo "VERSION=$(echo $version)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: auth_to_gcp
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}/locations/global/workloadIdentityPools/rbc-github-pool/providers/${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          audience: ${{ secrets.WORKLOAD_IDENTITY_AUD }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
      - run: |-
          gcloud auth configure-docker

      - name: 'Build docker image with database password and Version tag'
        if: ${{ inputs.docker-database-build-arg }}
        run: |-
          docker build --build-arg PASSWORD=${{ secrets.DATABASE_PASSWORD }} --build-arg ACTIVE_PROFILE=prod --tag "$DOCKER_IMAGE_NAME:$VERSION" .
          docker build --build-arg PASSWORD=root --build-arg ACTIVE_PROFILE=local --tag "$DOCKER_IMAGE_NAME:local_latest" .
          
      - name: 'Build docker image with Version tag'
        if: ${{ !inputs.docker-database-build-arg }}
        run: |-
          docker build --build-arg ACTIVE_PROFILE=prod --tag "$DOCKER_IMAGE_NAME:$VERSION" .
          docker build --build-arg ACTIVE_PROFILE=local --tag "$DOCKER_IMAGE_NAME:local_latest" .

      - name: 'Publish docker image'
        run: |-
          docker push "$DOCKER_IMAGE_NAME:$VERSION"
          docker push "$DOCKER_IMAGE_NAME:local_latest"

      - name: 'Deploy Docker image to Compute engine'
        run: |-
          gcloud compute ssh --project=${{ secrets.GCE_PROJECT }} --zone=$GCE_INSTANCE_ZONE --ssh-key-expire-after=5m --command="bash ${{ inputs.update-script }} $VERSION" $GCE_INSTANCE

      - name: 'Sleep for 1 minute'
        run: sleep 1m
        shell: bash

      - name: 'Check are all docker containers running'
        run: |-
          gcloud compute ssh --project=${{ secrets.GCE_PROJECT }} --zone=$GCE_INSTANCE_ZONE --ssh-key-expire-after=5m --command="sudo docker ps -a" $GCE_INSTANCE
